version: 2
updates:
- package-ecosystem: gradle
  directory: "/ChBoSync_AndroidStudioProject"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
